apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: grpc-k8s-deployer
build:
  artifacts:
  - image: localhost:5000/grpc-deployer-server
    docker:
      dockerfile: server/Dockerfile
  - image: localhost:5000/grpc-deployer-client
    docker:
      dockerfile: client/Dockerfile
  local:
    useBuildkit: true
    push: true
deploy:
  kubectl:
    manifests:
    - k8s/rbac.yaml
    - k8s/server-deployment.yaml
    - k8s/client-job.yaml